version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/app/src
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/database:/usr/src/app/database
    privileged: true


